import React, {FC, useEffect} from 'react';
import {Route} from "react-router-dom";

import {Product} from "../../../types/types";
import PerfumeListComponent from "./PerfumeListComponent";
import ScrollButton from "../../../component/ScrollButton/ScrollButton";

const PerfumeList: FC = () => {
    const perfumes: Array<Product> = [{id: 1,
        productName: 'R312',
        year: 2000,
        country: 'Vietnam',
        productCategory: 'Mouse',
        description: 'string',
        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
        brand: 'Razer',
        price: 100},{id: 1,
            productName: 'R312',
            year: 2000,
            country: 'Vietnam',
            productCategory: 'Mouse',
            description: 'string',
            picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
            brand: 'Razer',
            price: 100},{id: 1,
                productName: 'R312',
                year: 2000,
                country: 'Vietnam',
                productCategory: 'Mouse',
                description: 'string',
                picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                brand: 'Razer',
                price: 100},{id: 1,
                    productName: 'R312',
                    year: 2000,
                    country: 'Vietnam',
                    productCategory: 'Mouse',
                    description: 'string',
                    picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                    brand: 'Razer',
                    price: 100},{id: 1,
                        productName: 'R312',
                        year: 2000,
                        country: 'Vietnam',
                        productCategory: 'Mouse',
                        description: 'string',
                        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                        brand: 'Razer',
                        price: 100},{id: 1,
                            productName: 'R312',
                            year: 2000,
                            country: 'Vietnam',
                            productCategory: 'Mouse',
                            description: 'string',
                            picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                            brand: 'Razer',
                            price: 100},{id: 1,
                                productName: 'R312',
                                year: 2000,
                                country: 'Vietnam',
                                productCategory: 'Mouse',
                                description: 'string',
                                picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                brand: 'Razer',
                                price: 100},{id: 1,
                                    productName: 'R312',
                                    year: 2000,
                                    country: 'Vietnam',
                                    productCategory: 'Mouse',
                                    description: 'string',
                                    picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                    brand: 'Razer',
                                    price: 100},{id: 1,
                                        productName: 'R312',
                                        year: 2000,
                                        country: 'Vietnam',
                                        productCategory: 'Mouse',
                                        description: 'string',
                                        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                        brand: 'Razer',
                                        price: 100},{id: 1,
                                            productName: 'R312',
                                            year: 2000,
                                            country: 'Vietnam',
                                            productCategory: 'Mouse',
                                            description: 'string',
                                            picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                            brand: 'Razer',
                                            price: 100},{id: 1,
                                                productName: 'R312',
                                                year: 2000,
                                                country: 'Vietnam',
                                                productCategory: 'Mouse',
                                                description: 'string',
                                                picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                brand: 'Razer',
                                                price: 100},{id: 1,
                                                    productName: 'R312',
                                                    year: 2000,
                                                    country: 'Vietnam',
                                                    productCategory: 'Mouse',
                                                    description: 'string',
                                                    picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                    brand: 'Razer',
                                                    price: 100},{id: 1,
                                                        productName: 'R312',
                                                        year: 2000,
                                                        country: 'Vietnam',
                                                        productCategory: 'Mouse',
                                                        description: 'string',
                                                        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                        brand: 'Razer',
                                                        price: 100},{id: 1,
                                                            productName: 'R312',
                                                            year: 2000,
                                                            country: 'Vietnam',
                                                            productCategory: 'Mouse',
                                                            description: 'string',
                                                            picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                            brand: 'Razer',
                                                            price: 100},{id: 1,
                                                                productName: 'R312',
                                                                year: 2000,
                                                                country: 'Vietnam',
                                                                productCategory: 'Mouse',
                                                                description: 'string',
                                                                picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                                brand: 'Razer',
                                                                price: 100},{id: 1,
                                                                    productName: 'R312',
                                                                    year: 2000,
                                                                    country: 'Vietnam',
                                                                    productCategory: 'Mouse',
                                                                    description: 'string',
                                                                    picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                                    brand: 'Razer',
                                                                    price: 100},{id: 1,
                                                                        productName: 'R312',
                                                                        year: 2000,
                                                                        country: 'Vietnam',
                                                                        productCategory: 'Mouse',
                                                                        description: 'string',
                                                                        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                                        brand: 'Razer',
                                                                        price: 100},{id: 1,
                                                                            productName: 'R312',
                                                                            year: 2000,
                                                                            country: 'Vietnam',
                                                                            productCategory: 'Mouse',
                                                                            description: 'string',
                                                                            picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                                            brand: 'Razer',
                                                                            price: 100},{id: 1,
                                                                                productName: 'R312',
                                                                                year: 2000,
                                                                                country: 'Vietnam',
                                                                                productCategory: 'Mouse',
                                                                                description: 'string',
                                                                                picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                                                brand: 'Razer',
                                                                                price: 100},{id: 1,
                                                                                    productName: 'R312',
                                                                                    year: 2000,
                                                                                    country: 'Vietnam',
                                                                                    productCategory: 'Mouse',
                                                                                    description: 'string',
                                                                                    picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                                                    brand: 'Razer',
                                                                                    price: 100},{id: 1,
                                                                                        productName: 'R312',
                                                                                        year: 2000,
                                                                                        country: 'Vietnam',
                                                                                        productCategory: 'Mouse',
                                                                                        description: 'string',
                                                                                        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                                                                        brand: 'Razer',
                                                                                        price: 100},{id: 1,
        productName: 'R312',
        year: 2000,
        country: 'Vietnam',
        productCategory: 'Mouse',
        description: 'string',
        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
        brand: 'Razer',
        price: 100},{id: 1,
            productName: 'R312',
            year: 2000,
            country: 'Vietnam',
            productCategory: 'Mouse',
            description: 'string',
            picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
            brand: 'Razer',
            price: 100},{id: 1,
                productName: 'R312',
                year: 2000,
                country: 'Vietnam',
                productCategory: 'Mouse',
                description: 'string',
                picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                brand: 'Razer',
                price: 100},{id: 1,
                    productName: 'R312',
                    year: 2000,
                    country: 'Vietnam',
                    productCategory: 'Mouse',
                    description: 'string',
                    picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                    brand: 'Razer',
                    price: 100},{id: 1,
                        productName: 'R312',
                        year: 2000,
                        country: 'Vietnam',
                        productCategory: 'Mouse',
                        description: 'string',
                        picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                        brand: 'Razer',
                        price: 100},{id: 1,
                            productName: 'R312',
                            year: 2000,
                            country: 'Vietnam',
                            productCategory: 'Mouse',
                            description: 'string',
                            picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                            brand: 'Razer',
                            price: 100},{id: 1,
                                productName: 'R312',
                                year: 2000,
                                country: 'Vietnam',
                                productCategory: 'Mouse',
                                description: 'string',
                                picturePath: 'https://m.media-amazon.com/images/I/516NCsvHpmL.jpg',
                                brand: 'Razer',
                                price: 100},
        
    
    ];


    useEffect(() => {
        //TODO fetch product
    }, []);

    const itemsPerPage = 24;
    const searchByData = [
        {label: 'Product Name', value: 'productName'},
        {label: 'Category', value: 'productCategory'},
        {label: 'Manufacturer country', value: 'country'},
        {label: 'Brand', value: 'brand'}
    ];

    return (
        <div className="container">
            <ScrollButton/>
            <Route exact component={() =>
                <PerfumeListComponent
                    data={perfumes}
                    itemsPerPage={itemsPerPage}
                    searchByData={searchByData}/>}/>
        </div>
    );
};

export default PerfumeList;
